# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort
      entry: isort
      language: python
      types: [python]
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
    - id: black
      name: black
      entry: black
      language: python
      language_version: python3.9
      types: [python]
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: python
      types: [python]
      args: [
        "-rn", # Only display messages
        "-sn", # Don't display the score
        "--rcfile=.pylintrc",
        "--ignore=E0401, C0413, C0415, R0914, C0103, W0104, W0621, W0703, C0301, R0915, E0611, R0801",
        "--recursive=y"
      ]
# - repo: local
#  hooks:
#    - id: pytest-check
#      name: pytest-check
#      entry: pytest
#      language: system
#      pass_filenames: false
#      always_run: true
#      files: ^tests/
