name: Push-to-EC2 and Upload to S3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # Upload file to S3
  upload:
    name: Upload to S3
    runs-on: ubuntu-latest
    
    steps:
      - name: Main Branch
        uses: actions/checkout@main

      - name: Upload File to Bucket
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl public-read
        env:
          AWS_REGION: "eu-west-1"
          S3_BUCKET: ${{ secrets.AWS_BUCKET }}
          S3_KEY: "data/tips.csv"
          FILE: "Waiter-Tips-Prediction/data/tips.csv"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}          
