name: Push-to-EC2 and Upload to S3

on:
  push:
    branches:
      - main

jobs:
  # Deploy code to EC2
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Files
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          SOURCE: "hsaltan/Machine-Learning/Waiter-Tips-Prediction/"

  # Upload file to S3
  upload:
      name: Upload to S3
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Upload file to bucket

        - uses: zdurham/s3-upload-github-action@master
          with:
            args: --acl public-read
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: "eu-west-1"
            S3_BUCKET: ${{ secrets.AWS_BUCKET }}
            S3_KEY: "data/tips.csv"
            FILE: "./Waiter-Tips-Prediction/data/tips.csv"
